import { FaGamepad } from "react-icons/fa";
import { GiWallet } from "react-icons/gi";
import { IoRibbonOutline } from "react-icons/io5";
import { MdDashboard, MdOutlineAddCard } from "react-icons/md";
import { PiUsersThreeLight } from "react-icons/pi";
import { RiAdvertisementLine, RiShoppingCartLine, RiUserLine } from "react-icons/ri";
import { TbSettings2, TbShoppingBag } from "react-icons/tb";

export const NAV_LINKS: NavLink[] = [
  {
    id: 1,
    title: "Explore",
    href: "/",
    type: "link",
  },
  { id: 2, title: "About Us", href: "/about", type: "link" },
  { id: 3, title: "Shop", href: "/shop", type: "link" },
  { id: 3, title: "Contact Us", href: "/contact", type: "link" },
];

export const testimonialImages = [
  {
    id: 0,
    text: "Our Testimonials",
    subText: "What People Say About Us",
  },
  {
    id: 1,
    image: "/images/testimonials/person2.jpg",
    name: "John Doe",
    position: "Designer",
    message:
      "Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem libero arcu ut. Lorem ips.",
    rating: 5,
  },
  {
    id: 2,
    image: "/images/testimonials/person4.jpg",
    name: "Jane Doe",
    position: "Developer",
    message:
      "Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem libero arcu ut. Lorem ips.",
    rating: 2,
  },
  {
    id: 3,
    image: "/images/testimonials/person3.jpg",
    name: "James Doe",
    position: "Customer Service",
    message:
      "Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem libero arcu ut. Lorem ips.",
    rating: 4,
  },
  {
    id: 4,
    image: "/images/testimonials/person1.jpg",
    name: "Doe Jame",
    position: "Customer Service",
    message:
      "Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut.Lorem ipsum dolor sit amet ctetur. Lorem libero arcu ut. Lorem libero arcu ut. Lorem ips.",
    rating: 3,
  },
];

export const CATEGORIES = [
  // "All Categories",
  "Clothings",
  "Electronic Gadgets",
  "Groceries",
  "For Women",
  "Body Cream & Oil",
  "Furniture",
  "TV & Homes Appliances",
  "Watches & Accessories",
];
export const VENDORS = [
  // "All Vendors",
  "Premium Vendors",
  "Skishop",
  "basic Vendors",
];

// Admin navigation items
export const adminSideItems = [
  {
    route: "Dashboard",
    link: "/admin/home",
    icon: MdDashboard,
    id: "home",
  },
  {
    route: "Users",
    link: "/admin/users",
    icon: PiUsersThreeLight,
    id: "users",
  },
  {
    route: "Orders",
    link: "/admin/orders",
    icon: RiShoppingCartLine,
    id: "orders",
  },
  {
    route: "Payouts",
    link: "/admin/payouts",
    icon: MdOutlineAddCard,
    id: "payouts",
  },
  {
    route: "Skicom Products",
    link: "/admin/products",
    icon: TbShoppingBag,
    id: "skicom-products",
  },
  {
    route: "Revenues",
    link: "/admin/revenues",
    icon: GiWallet,
    id: "revenues",
  },
  {
    route: "Subscriptions",
    link: "/admin/subscriptions",
    icon: IoRibbonOutline,
    id: "subscriptions",
  },
  {
    route: "Promotions & ads",
    link: "/admin/promotions",
    icon: RiAdvertisementLine,
    id: "promotions",
  },
  {
    route: "Play 2 win",
    link: "/admin/promotions",
    icon: FaGamepad,
    id: "play-to-win",
  },
  {
    route: "Settings",
    link: "/admin/settings",
    icon: TbSettings2,
    id: "settings",
  },
];

// Vendor navigation items
export const vendorSideItems = [
  {
    route: "Home",
    link: "/dashboard/home",
    icon: MdDashboard,
    id: "home",
  },
  {
    route: "Products",
    link: "/dashboard/products",
    icon: TbShoppingBag,
    id: "products",
  },
  {
    route: "Orders",
    link: "/dashboard/orders",
    icon: RiShoppingCartLine,
    id: "orders",
  },
  {
    route: "Profile",
    link: "/dashboard/profile",
    icon: RiUserLine,
    id: "profile",
  },
  {
    route: "Payouts",
    link: "/dashboard/payouts",
    icon: MdOutlineAddCard,
    id: "payouts",
  },
  {
    route: "Settings",
    link: "/dashboard/settings",
    icon: TbSettings2,
    id: "settings",
  },
];

// Super Admin navigation items (includes all admin items plus super admin specific ones)
export const superAdminSideItems = [
  ...adminSideItems,
  {
    route: "Super Admin",
    link: "/super-admin/dashboard",
    icon: MdDashboard,
    id: "super-admin",
  },
  {
    route: "Admin Management",
    link: "/super-admin/admin-management",
    icon: PiUsersThreeLight,
    id: "admin-management",
  },
  {
    route: "System Settings",
    link: "/super-admin/system-settings",
    icon: TbSettings2,
    id: "system-settings",
  },
  {
    route: "Audit Logs",
    link: "/super-admin/audit-logs",
    icon: RiAdvertisementLine,
    id: "audit-logs",
  },
];

// Legacy export for backward compatibility
export const sideItems = adminSideItems;

// Define columns for the table
export const employeeColumns = [
  {
    id: "name",
    header: "Name",
    accessorKey: "name",
  },
  {
    id: "email",
    header: "Email",
    accessorKey: "email",
  },
  {
    id: "department",
    header: "Department",
    accessorKey: "department",
  },
  {
    id: "role",
    header: "Role",
    accessorKey: "role",
  },
  {
    id: "status",
    header: "Status",
    accessorKey: "status",
  },
  {
    id: "joinDate",
    header: "Join Date",
    accessorKey: "joinDate",
  },
];

export const productStatusOptions = [
  { value: "all", label: "All" },
  { value: "published", label: "Published" },
  { value: "draft", label: "Draft" },
];
export const orderStatusOptions = [
  { value: "all", label: "All" },
  { value: "delivered", label: "Delivered" },
  { value: "pending", label: "Pending" },
  { value: "cancelled", label: "Cancelled" },
];

export const countries = [
  { value: "afghanistan", label: "🇦🇫 Afghanistan" },
  { value: "albania", label: "🇦🇱 Albania" },
  { value: "algeria", label: "🇩🇿 Algeria" },
  { value: "andorra", label: "🇦🇩 Andorra" },
  { value: "angola", label: "🇦🇴 Angola" },
  { value: "antigua_and_barbuda", label: "🇦🇬 Antigua and Barbuda" },
  { value: "argentina", label: "🇦🇷 Argentina" },
  { value: "armenia", label: "🇦🇲 Armenia" },
  { value: "australia", label: "🇦🇺 Australia" },
  { value: "austria", label: "🇦🇹 Austria" },
  { value: "azerbaijan", label: "🇦🇿 Azerbaijan" },
  { value: "bahamas", label: "🇧🇸 Bahamas" },
  { value: "bahrain", label: "🇧🇭 Bahrain" },
  { value: "bangladesh", label: "🇧🇩 Bangladesh" },
  { value: "barbados", label: "🇧🇧 Barbados" },
  { value: "belarus", label: "🇧🇾 Belarus" },
  { value: "belgium", label: "🇧🇪 Belgium" },
  { value: "belize", label: "🇧🇿 Belize" },
  { value: "benin", label: "🇧🇯 Benin" },
  { value: "bhutan", label: "🇧🇹 Bhutan" },
  { value: "bolivia", label: "🇧🇴 Bolivia" },
  { value: "bosnia_and_herzegovina", label: "🇧🇦 Bosnia and Herzegovina" },
  { value: "botswana", label: "🇧🇼 Botswana" },
  { value: "brazil", label: "🇧🇷 Brazil" },
  { value: "brunei", label: "🇧🇳 Brunei" },
  { value: "bulgaria", label: "🇧🇬 Bulgaria" },
  { value: "burkina_faso", label: "🇧🇫 Burkina Faso" },
  { value: "burundi", label: "🇧🇮 Burundi" },
  { value: "cambodia", label: "🇰🇭 Cambodia" },
  { value: "cameroon", label: "🇨🇲 Cameroon" },
  { value: "canada", label: "🇨🇦 Canada" },
  { value: "cape_verde", label: "🇨🇻 Cape Verde" },
  { value: "central_african_republic", label: "🇨🇫 Central African Republic" },
  { value: "chad", label: "🇹🇩 Chad" },
  { value: "chile", label: "🇨🇱 Chile" },
  { value: "china", label: "🇨🇳 China" },
  { value: "colombia", label: "🇨🇴 Colombia" },
  { value: "comoros", label: "🇰🇲 Comoros" },
  { value: "congo", label: "🇨🇬 Congo" },
  { value: "costa_rica", label: "🇨🇷 Costa Rica" },
  { value: "croatia", label: "🇭🇷 Croatia" },
  { value: "cuba", label: "🇨🇺 Cuba" },
  { value: "cyprus", label: "🇨🇾 Cyprus" },
  { value: "czech_republic", label: "🇨🇿 Czech Republic" },
  { value: "denmark", label: "🇩🇰 Denmark" },
  { value: "djibouti", label: "🇩🇯 Djibouti" },
  { value: "dominica", label: "🇩🇲 Dominica" },
  { value: "dominican_republic", label: "🇩🇴 Dominican Republic" },
  { value: "ecuador", label: "🇪🇨 Ecuador" },
  { value: "egypt", label: "🇪🇬 Egypt" },
  { value: "el_salvador", label: "🇸🇻 El Salvador" },
  { value: "equatorial_guinea", label: "🇬🇶 Equatorial Guinea" },
  { value: "eritrea", label: "🇪🇷 Eritrea" },
  { value: "estonia", label: "🇪🇪 Estonia" },
  { value: "ethiopia", label: "🇪🇹 Ethiopia" },
  { value: "fiji", label: "🇫🇯 Fiji" },
  { value: "finland", label: "🇫🇮 Finland" },
  { value: "france", label: "🇫🇷 France" },
  { value: "gabon", label: "🇬🇦 Gabon" },
  { value: "gambia", label: "🇬🇲 Gambia" },
  { value: "georgia", label: "🇬🇪 Georgia" },
  { value: "germany", label: "🇩🇪 Germany" },
  { value: "ghana", label: "🇬🇭 Ghana" },
  { value: "greece", label: "🇬🇷 Greece" },
  { value: "grenada", label: "🇬🇩 Grenada" },
  { value: "guatemala", label: "🇬🇹 Guatemala" },
  { value: "guinea", label: "🇬🇳 Guinea" },
  { value: "guinea_bissau", label: "🇬🇼 Guinea-Bissau" },
  { value: "guyana", label: "🇬🇾 Guyana" },
  { value: "haiti", label: "🇭🇹 Haiti" },
  { value: "honduras", label: "🇭🇳 Honduras" },
  { value: "hungary", label: "🇭🇺 Hungary" },
  { value: "iceland", label: "🇮🇸 Iceland" },
  { value: "india", label: "🇮🇳 India" },
  { value: "indonesia", label: "🇮🇩 Indonesia" },
  { value: "iran", label: "🇮🇷 Iran" },
  { value: "iraq", label: "🇮🇶 Iraq" },
  { value: "ireland", label: "🇮🇪 Ireland" },
  { value: "israel", label: "🇮🇱 Israel" },
  { value: "italy", label: "🇮🇹 Italy" },
  { value: "jamaica", label: "🇯🇲 Jamaica" },
  { value: "japan", label: "🇯🇵 Japan" },
  { value: "jordan", label: "🇯🇴 Jordan" },
  { value: "kazakhstan", label: "🇰🇿 Kazakhstan" },
  { value: "kenya", label: "🇰🇪 Kenya" },
  { value: "kiribati", label: "🇰🇮 Kiribati" },
  { value: "north_korea", label: "🇰🇵 North Korea" },
  { value: "south_korea", label: "🇰🇷 South Korea" },
  { value: "kuwait", label: "🇰🇼 Kuwait" },
  { value: "kyrgyzstan", label: "🇰🇬 Kyrgyzstan" },
  { value: "laos", label: "🇱🇦 Laos" },
  { value: "latvia", label: "🇱🇻 Latvia" },
  { value: "lebanon", label: "🇱🇧 Lebanon" },
  { value: "lesotho", label: "🇱🇸 Lesotho" },
  { value: "liberia", label: "🇱🇷 Liberia" },
  { value: "libya", label: "🇱🇾 Libya" },
  { value: "liechtenstein", label: "🇱🇮 Liechtenstein" },
  { value: "lithuania", label: "🇱🇹 Lithuania" },
  { value: "luxembourg", label: "🇱🇺 Luxembourg" },
  { value: "madagascar", label: "🇲🇬 Madagascar" },
  { value: "malawi", label: "🇲🇼 Malawi" },
  { value: "malaysia", label: "🇲🇾 Malaysia" },
  { value: "maldives", label: "🇲🇻 Maldives" },
  { value: "mali", label: "🇲🇱 Mali" },
  { value: "malta", label: "🇲🇹 Malta" },
  { value: "marshall_islands", label: "🇲🇭 Marshall Islands" },
  { value: "mauritania", label: "🇲🇷 Mauritania" },
  { value: "mauritius", label: "🇲🇺 Mauritius" },
  { value: "mexico", label: "🇲🇽 Mexico" },
  { value: "micronesia", label: "🇫🇲 Micronesia" },
  { value: "moldova", label: "🇲🇩 Moldova" },
  { value: "monaco", label: "🇲🇨 Monaco" },
  { value: "mongolia", label: "🇲🇳 Mongolia" },
  { value: "montenegro", label: "🇲🇪 Montenegro" },
  { value: "morocco", label: "🇲🇦 Morocco" },
  { value: "mozambique", label: "🇲🇿 Mozambique" },
  { value: "myanmar", label: "🇲🇲 Myanmar" },
  { value: "namibia", label: "🇳🇦 Namibia" },
  { value: "nauru", label: "🇳🇷 Nauru" },
  { value: "nepal", label: "🇳🇵 Nepal" },
  { value: "netherlands", label: "🇳🇱 Netherlands" },
  { value: "new_zealand", label: "🇳🇿 New Zealand" },
  { value: "nicaragua", label: "🇳🇮 Nicaragua" },
  { value: "niger", label: "🇳🇪 Niger" },
  { value: "nigeria", label: "🇳🇬 Nigeria" },
  { value: "norway", label: "🇳🇴 Norway" },
  { value: "oman", label: "🇴🇲 Oman" },
  { value: "pakistan", label: "🇵🇰 Pakistan" },
  { value: "palau", label: "🇵🇼 Palau" },
  { value: "palestine", label: "🇵🇸 Palestine" },
  { value: "panama", label: "🇵🇦 Panama" },
  { value: "papua_new_guinea", label: "🇵🇬 Papua New Guinea" },
  { value: "paraguay", label: "🇵🇾 Paraguay" },
  { value: "peru", label: "🇵🇪 Peru" },
  { value: "philippines", label: "🇵🇭 Philippines" },
  { value: "poland", label: "🇵🇱 Poland" },
  { value: "portugal", label: "🇵🇹 Portugal" },
  { value: "qatar", label: "🇶🇦 Qatar" },
  { value: "romania", label: "🇷🇴 Romania" },
  { value: "russia", label: "🇷🇺 Russia" },
  { value: "rwanda", label: "🇷🇼 Rwanda" },
  { value: "saint_kitts_and_nevis", label: "🇰🇳 Saint Kitts and Nevis" },
  { value: "saint_lucia", label: "🇱🇨 Saint Lucia" },
  { value: "saint_vincent", label: "🇻🇨 Saint Vincent and the Grenadines" },
  { value: "samoa", label: "🇼🇸 Samoa" },
  { value: "san_marino", label: "🇸🇲 San Marino" },
  { value: "sao_tome_and_principe", label: "🇸🇹 São Tomé and Príncipe" },
  { value: "saudi_arabia", label: "🇸🇦 Saudi Arabia" },
  { value: "senegal", label: "🇸🇳 Senegal" },
  { value: "serbia", label: "🇷🇸 Serbia" },
  { value: "seychelles", label: "🇸🇨 Seychelles" },
  { value: "sierra_leone", label: "🇸🇱 Sierra Leone" },
  { value: "singapore", label: "🇸🇬 Singapore" },
  { value: "slovakia", label: "🇸🇰 Slovakia" },
  { value: "slovenia", label: "🇸🇮 Slovenia" },
  { value: "solomon_islands", label: "🇸🇧 Solomon Islands" },
  { value: "somalia", label: "🇸🇴 Somalia" },
  { value: "south_africa", label: "🇿🇦 South Africa" },
  { value: "south_sudan", label: "🇸🇸 South Sudan" },
  { value: "spain", label: "🇪🇸 Spain" },
  { value: "sri_lanka", label: "🇱🇰 Sri Lanka" },
  { value: "sudan", label: "🇸🇩 Sudan" },
  { value: "suriname", label: "🇸🇷 Suriname" },
  { value: "sweden", label: "🇸🇪 Sweden" },
  { value: "switzerland", label: "🇨🇭 Switzerland" },
  { value: "syria", label: "🇸🇾 Syria" },
  { value: "taiwan", label: "🇹🇼 Taiwan" },
  { value: "tajikistan", label: "🇹🇯 Tajikistan" },
  { value: "tanzania", label: "🇹🇿 Tanzania" },
  { value: "thailand", label: "🇹🇭 Thailand" },
  { value: "timor_leste", label: "🇹🇱 Timor-Leste" },
  { value: "togo", label: "🇹🇬 Togo" },
  { value: "tonga", label: "🇹🇴 Tonga" },
  { value: "trinidad_and_tobago", label: "🇹🇹 Trinidad and Tobago" },
  { value: "tunisia", label: "🇹🇳 Tunisia" },
  { value: "turkey", label: "🇹🇷 Turkey" },
  { value: "turkmenistan", label: "🇹🇲 Turkmenistan" },
  { value: "tuvalu", label: "🇹🇻 Tuvalu" },
  { value: "uganda", label: "🇺🇬 Uganda" },
  { value: "ukraine", label: "🇺🇦 Ukraine" },
  { value: "united_arab_emirates", label: "🇦🇪 United Arab Emirates" },
  { value: "united_kingdom", label: "🇬🇧 United Kingdom" },
  { value: "united_states", label: "🇺🇸 United States" },
  { value: "uruguay", label: "🇺🇾 Uruguay" },
  { value: "uzbekistan", label: "🇺🇿 Uzbekistan" },
  { value: "vanuatu", label: "🇻🇺 Vanuatu" },
  { value: "vatican_city", label: "🇻🇦 Vatican City" },
  { value: "venezuela", label: "🇻🇪 Venezuela" },
  { value: "vietnam", label: "🇻🇳 Vietnam" },
  { value: "yemen", label: "🇾🇪 Yemen" },
  { value: "zambia", label: "🇿🇲 Zambia" },
  { value: "zimbabwe", label: "🇿🇼 Zimbabwe" },
];

export const months = [
  { value: "1", label: "January" },
  { value: "2", label: "February" },
  { value: "3", label: "March" },
  { value: "4", label: "April" },
  { value: "5", label: "May" },
  { value: "6", label: "June" },
  { value: "7", label: "July" },
  { value: "8", label: "August" },
  { value: "9", label: "September" },
  { value: "10", label: "October" },
  { value: "11", label: "November" },
  { value: "12", label: "December" },
];

export const OUR_STRENGTH = [
  {
    title: "Secured Payment",
    description: "Secure, instant payments and transactions with our integrated financial solution.",
    image: "/images/about/illustration-1.svg",
  },
  {
    title: "Fast Delivery",
    description: "Secure, instant payments and transactions with our integrated financial solution.",
    image: "/images/about/illustration-2.svg",
  },
  {
    title: "Verified Vendors",
    description: "Secure, instant payments and transactions with our integrated financial solution.",
    image: "/images/about/illustration-3.svg",
  },
  {
    title: "Seamless Experience",
    description: "Secure, instant payments and transactions with our integrated financial solution.",
    image: "/images/about/illustration-4.svg",
  },
];
